jobs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),

    ] + static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('treasures/', include('treasures.urls')),
    path('profile/', include('jobs.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

treasures/urls.py
from django.urls import path
from . import views

app_name = 'treasures'
urlpatterns = [
    path('home/', views.homeindex.as_view(), name='home'),
    path('<int:val>/', views.detail, name='detail'),
    path('add/', views.add_new, name='new_treasure'),
    path('<int:val>/edit/', views.edit_treasure, name='edit_treasure'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

jobs/models.py
from django.db import models


class Home(models.Model):
    image = models.ImageField(upload_to='image/')
    summary = models.CharField(max_length=300)


class Details(models.Model):
    image = models.ImageField(upload_to='image/')
    title = models.CharField(max_length=200)
    date = models.DateField()
    description = models.CharField(max_length=300)

portfolio/models.py
from django.db import models

# Create your models here.

treasures/models.py
from django.db import models

# Create your models here.
class treasureGram(models.Model):
    name = models.CharField(max_length=50)
    value = models.DecimalField(max_digits=12, decimal_places=2)
    material = models.CharField(max_length=20)
    location = models.CharField(max_length=100)
    image_url = models.CharField(max_length=400)

    def __str__(self):
        return self.name

jobs/views.py
from django.shortcuts import render,redirect
from .models import Home
from django.http import HttpResponse

def home(request):
    all_jobs = Home.objects.all()
    return render(request, 'jobs/home.html', {'all_jobs':all_jobs})

portfolio/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'portfolio/home.html')

treasures/views.py
from django.contrib import auth
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import treasureGram
from .froms import treasureForm
from django.views import generic

# Create your views here.
class homeindex(generic.ListView):
    template_name = 'treasures/home.html'
    context_object_name = 'all_treasures'

    def get_queryset(self):
        return  treasureGram.objects.all()


def detail(request, val):
    treasure = treasureGram.objects.get(id =val)
    return render(request, 'treasures/detail.html', {'treasure': treasure})

def add_new(request):
    if request.method == 'POST':
        form = treasureForm(request.POST)
        if form.is_valid():
            treasure = form.save()
            treasure.save()
            return redirect('/')

    else:
        form = treasureForm()
        return render(request, 'treasures/new_treasure.html', {'form':form})

def edit_treasure(request, val):
    treasure = get_object_or_404(treasureGram, pk=val)
    if request.method=='POST':
        form = treasureForm(request.POST, instance=treasure)
        if form.is_valid():
            treasure = form.save()
            treasure.save()
            return redirect('treasures:detail', val=treasure.pk)
    else:
        form = treasureForm(instance=treasure)
        return render(request,'treasures/edit_treasure.html',{'form':form})


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email_id']
        password = request.POST['password']

        user = User.objects.create_user(username=username, first_name=firstname, last_name=lastname, email=email, password=password)
        user.save()
        print("user created")
        return redirect('/')

    else:
         return render(request, 'treasures/signup.html')


def login(request):
    if request.method == 'POST':
        username1 = request.POST['username']
        password1 = request.POST['password']
        from django.contrib import auth
        user = auth.authenticate(username=username1, password=password1)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            return HttpResponse('<h1 class="alert alert-success">incorrect password or username</h1>')

    else:
        return render(request,'treasures/login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

jobs/templates/jobs/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>

<nav style="background-color:gray" class="navbar-expand-sm navbar-light ">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarico">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarico">

       <ul class="navbar-nav ml-auto">

                     <button type="button" class="btn btn-sm btn-outline-secondery">Home</button>
       </ul>
    </div>
</nav>
<p>
<div class="container text-center">
<h2 class="alert alert-success">
    Welcome to your photo gallery
</h2>

</div>
</p>

<div class="album py-5 bg-light">
    <div style="...." class="container text-center">
        <div class="row">
          {% for job in all_jobs %}
            <div class="col-sm-4">
                <div class="card mb-4 box-shadow">
                     <img style="...." class="card-img-top" src="{{ job.image.url }}">
                     <p>{{ job.summary }}</p>

                       <button type="button" class="btn btn-sm btn-outline-secondery">View</button>


                </div>
            </div>
          {% endfor %}
        </div>
    </div>
</div>
</body>
</html>

portfolio/templates/portfolio/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Farzana_Bulbul_portfolio</title>
	<meta charset="UTF-8">
	 {% load static %}

	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700 }" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

	<div id="wrapper">
		<!-- Header Begin -->
		<header id="header">
			<!-- Menu and Logo Begin -->
			<div class="top_menu">
				<div class="center">
					<figure class="logo">
						{% comment %} <a href="#" title="logo"> {% endcomment %}
						<h2 height="200" style="color:white ; padding-top: 10px;"><b>Farzana Bulbul</b></h2>
						{% comment %} <img src=" static/img/logo.png"  alt="logo"> {% endcomment %}
					</figure>
					<nav class="menu">
						<ul>
							<li><a href="#" title="Home" class="menu_list">Home</a></li>
							<li><a href="#about" title="About" class="menu_list">About Me</a></li>
							<li><a href="#education" title="Education" class="menu_list">Education</a></li>
							<li><a href="#portfolio" title="Portfolio" class="menu_list">Projects</a></li>
							<li><a href="#contact" title="Contact" class="menu_list">Contact</a></li>
						</ul>
					</nav>
					<div class="mob_menu_btn"><i class="fas fa-bars"></i></div>
				</div>
			</div>
			<!-- Menu and Logo End -->
			<!-- Header content Begin -->
			<section class="main_content">
				<div class="center">
					<h3>Passionate backend developer crafting clean, efficient, and meaningful solutions </h3>
					<!-- Filled with javascript -->
				</div>
			</section>
			<!-- Header Content End -->
			<!-- Socials Links Begin -->
			<div class="center">
				<nav class="socials">
					<ul>
						<li><a href="https://www.facebook.com/farzanabulbul.meghla" title="Facebook" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
						<li><a href="https://www.linkedin.com/in/farzana-bulbul-097b49198/" title="LinkedIn" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
					</ul>
				</nav>
			</div>
			<!-- Socials Links End -->
			<!-- Scroll Button Begin -->
			<section class="scroll">
				<div class="center">
					<h6>Scroll for more</h6>
					<i class="far fa-arrow-alt-circle-down"></i>
				</div>
			</section>
			<!-- Scroll Button End -->
		</header>
		<!-- Header End -->
		<!-- Content Begin -->
		<section class="content">

			<!-- About Begin -->
			<section class="about" id="about">
				<div class="center">
					<h2>About Me</h2>
					<div class="personal_data">
						<figure><img src="static/img/user.jpg" alt="user image"></figure>
						<ul class="personal_data_list">
							<li><strong>Name:</strong>Farzana Bulbul</li>
							<li><strong>Email:</strong>farzanaece2k15@gmail.com</li>
							<li><strong>Nationality:</strong>Bangladeshi</li>
						</ul>
					</div>


					<section class="about_description">
						<h2>Personal Review</h2>
						<p> I am a dedicated Software Engineer with a strong foundation in backend development and hands-on experience across multiple domains.
							 After completing my B.Sc., I began my career as a Junior Software Developer, where I worked on a Django-based project, focusing primarily on backend development. 
							 I then joined another company as a Software Engineer and contributed to building and maintaining an e-commerce website, again specializing in backend systems.
							Most recently, I have been working at RedDot Digital Limited for the past year as an Operations Engineer, where I gained valuable insight into the operational aspects of software systems and how they run in production.
							This diverse experience has helped me grow as a well-rounded engineer with both development and operational expertise.
						</p>
						<p>
                           Now, I am looking forward to contributing my knowledge and experience to the software industry in a meaningful and impactful way.
                        </p>
					</section>

				</div>
			</section>
			<!-- About End -->

			<!-- Skills Begin -->
			<section class="skills" id="skills">
				<div class="center">
					<h2>Skills</h2>
					<ul class="skills_list">
						<li>
							<h2>python</h2>
							<div class="progress-bar blue stripes">
								<span style="width: 70%"></span>
							</div>
						</li>
						<li>
							<h2>html</h2>
							<div class="progress-bar blue stripes">
								<span style="width: 80%"></span>
							</div>
						</li>
						<li>
							<h2>Django</h2>
							<div class="progress-bar blue stripes">
								<span style="width: 70%"></span>
							</div>
						</li>

						<li>
							<h2>React</h2>
							<div class="progress-bar blue stripes">
								<span style="width: 40%"></span>
							</div>
						</li>

					</ul>
				</div>
			</section>
			<!-- Skills End -->

			<!-- Portfolio Begin -->
			<section class="portfolio" id="portfolio">
				<div class="center">
					<h2>Projects</h2>
					<ul class="portfolio_links">
						<li><a data-filter="#" href="http://127.0.0.1:8000/treasures/home">Treasurehunt</a></li>
						<li><a data-filter="#"  href="http://127.0.0.1:8000/profile">Photo gallery</a></li>

						</ul>
					<ul class="portfolio_tabs">
						<li class="item wordpress">
							<a href="#" title="Portfolio"><img src="static/img/work.PNG" alt="work"></a>
							<div class="portfolio_data">
								<a href="#" title="Portfolio"><h2>Project 1</h2></a>
							</div>
						</li>
						<li class="item web wordpress">
							<a href="#" title="Portfolio"><img src="static/img/1.png" alt="work"></a>
							<div class="portfolio_data">
								<a href="#" title="Portfolio"><h2>Project 2</h2></a>
							</div>
						</li>

					</ul>
				</div>
			</section>
			<!-- Portfolio End -->

			<div class="center">
				<!-- Education Begin -->
				<section class="education" id="education">
					<h2>Education</h2>
					<ul class="timeline">
						<li><a href="#" title="Education">2016 - 2020 Bachelor Degree in Electronics and Communication Engineering, "Khulna University of Engineering and Technology" </a></li>
						<li><a href="#" title="Education">2013-2015 HSC from "Govt. Girls’ College, Khulna"</a></li>
						<li><a href="#" title="Education">2013 SHC from "Nau Bahini Secondary School,Khulna"</a></li>
					</ul>
				</section>
				<!-- Education End -->
			</div>


			<!-- Stats Begin -->
			<div class="stats">
				<div class="center">
					<ul>
						<li>
							<a href="#" title="Stats"><i class="fas fa-trophy"></i></a>
							<a href="#" title="Stats"><h3>Licenses and Certification </h3></a>
							<a href="#" title="Stats"><h2>3</h2></a>
						</li>
						<li>
							<a href="#" title="Stats"><i class="fas fa-briefcase"></i></a>
							<a href="#" title="Stats"><h3>Projects</h3></a>
							<a href="#" title="Stats"><h2>3</h2></a>
						</li>
						<li>
							<a href="#" title="Stats"><i class="fas fa-briefcase"></i></a>
							<a href="#" title="Stats"><h3>Courses</h3></a>
							<a href="#" title="Stats"><h2>3</h2></a>
						</li>
					</ul>
				</div>
			</div>
			<!-- Stats End -->


			<!-- Contact Begin -->
			<section class="contact" id="contact">
				<div class="center">
					<h2>Contact me</h2>
					<form class="contact_form">
						<input type="text" name="name" class="cf_name" placeholder="Name">
						<input type="email" name="email" class="cf_email" placeholder="Email">
						<textarea name="message" class="cf_message" placeholder="Message"></textarea>
						<input type="submit" value="SEND" class="cf_submit">
					</form>
				</div>
			</section>
		</section>
		<!-- Content End -->

		<footer id="footer">
			<div class="center">
				<p>© 2018 https://www.site.com</p>
			</div>
		</footer>

	</div>
	<script src="static/js/jquery-2.1.4.min.js"></script>
	<script src="static/js/imagesloaded.pkgd.min.js"></script>
	<script src="static/js/isotope.pkgd.min.js"></script>
	<script src="static/js/typed.min.js"></script>
	<script src="static/js/script.js"></script>
</body>
</html>

treasures/templates/treasures/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'treasures/style.css' %}">

</head>
<body>
<nav style="background-color:gray" class="navbar-expand-sm navbar-light ">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
             <a class="nav-link" href="{% url 'treasures:home' %}">
                 <button type="button" class="btn btn-sm btn-outline-secondery">Homepage</button>
             </a>
        </li>
    </ul>
</nav>
     {% block content %}

     {% endblock %}

</body>
</html>

treasures/templates/treasures/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}

    <div class="container text-center">
        <h1>This is Our Detail Page</h1>
        <h1 class="alert alert-success">{{treasure.name}} </h1>
        <p>
           Value: {{treasure.value}}<br>
           Material: {{treasure.material}}<br>
           Location: {{treasure.location}}<br>
           <img src="{{treasure.image_url}}">
        </p>

    </div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/edit_treasure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}
<div class="container text-center">
    <p>
        <h3 class="alert alert-success">Edit the treasure </h3>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
               <button type="submit">Save</button>
            </form>
    </p>
</div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static 'treasures/style.css' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
<nav style="background-color:gray" class="navbar-expand-sm navbar-light ">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarico">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarico">

       <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <a href="{% url 'treasures:logout' %}">
                     <button type="button" class="btn btn-sm btn-outline-secondery">logout</button>
                </a>
       </ul>
       <ul class="navbar-nav ml-auto">
                {% else %}
                <a href="{% url 'treasures:signup' %}">
                    <button type="button" class="btn btn-sm btn-outline-secondery">Not_Regestered?signup</button>
                </a>

                <a href="{% url 'treasures:login' %}">
                    <button type="button" class="btn btn-sm btn-outline-secondery">Regestered?login</button>
                </a>

       </ul>
           {% endif %}
    </div>
</nav>
<div class="album py-5 bg-light">
    <div style="...." class="container text-center">
       <h1  class="alert alert-success">this is homepage</h1>
        <div class="row">
          {% for treasure in all_treasures %}
            <div class="col-sm-4">
                <div class="card mb-4 box-shadow">
                     <img style="...." class="card-img-top" src="{{ treasure.image_url }}" alt="Treasure image">
                     <div class="card-body">
                          <h3>{{treasure.name}}</h3>
                       <div class="d-flex justify-content-between align-items-center">
                           <div class="btn-group">
                                 {% if user.is_authenticated %}
                                <a class="btn btn-primary" href="{% url 'treasures:detail' treasure.id %}">
                                   <button type="button" class="btn btn-sm btn-outline-secondery">View</button>
                                </a>
                                <a class="btn btn-primary" href="{% url 'treasures:edit_treasure' treasure.id %}">
                                   <button type="button" class="btn btn-sm btn-outline-secondery">Edit</button>
                                </a>
                                <a class="btn btn-primary" href="{% url 'treasures:new_treasure' %}">
                                    <button type="button" class="btn btn-sm btn-outline-secondery">Add new</button>
                                </a>
                                  {% else %}
                                <a class="btn btn-primary" href="{% url 'treasures:detail' treasure.id %}">
                                   <button type="button" class="btn btn-sm btn-outline-secondery">View</button>
                                </a>

                                   {% endif %}

                           </div>
                       </div>
                     </div>
                </div>
            </div>
          {% endfor %}
        </div>
    </div>
</div>


</body>
</html>

treasures/templates/treasures/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}

<div class="container text-center">
     <p>
        <h3 class="alert alert-success">Please put your correct username and password</h3>
        <form method="POST">
           {% csrf_token %}
           username:<input type="text" name="username">
           password:<input type="password" name="password">
           <input type="submit">
        </form>
     </p>
</div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/new_treasure.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}
<div class="container text-center">
    <p>
        <h1 class="alert alert-success">Add New Treasures</h1>
        <form method="post" class="treasureForm" >
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-warning" type="submit">save</button>
        </form>
    </p>
</div>
{% endblock %}
</body>
</html>

treasures/templates/treasures/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'treasures/base.html' %}
{% block content %}
<div class="container text-center">
    <p>
        <h1 class="alert alert-success">Fillup this form</h1>
 <form  method="POST">
    {% csrf_token %}
    user name:<input type="text" name="username"><br>
    first name:<input type="text" name="firstname"><br>
    last name:<input type="text" name="lastname"><br>
    email id:<input type="email" name="email_id"><br>
    password:<input type="password" name="password"><br>
    <input type="submit">
 </form></p>
</div>
{% endblock %}
</body>
</html>